version: 2

multi-ecosystem-groups:
  monthly-dependencies:
    schedule:
      interval: monthly
    commit-message:
      prefix: chore

updates:
  - package-ecosystem: gomod
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: monthly-dependencies

  - package-ecosystem: npm
    directory: /frontend
    patterns:
      - "*"
    multi-ecosystem-group: monthly-dependencies
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: monthly-dependencies

  - package-ecosystem: docker
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: monthly-dependencies
