package app

import (
	"embed"
	"io/fs"
	"mime"
	"net/http"
	"path"
	"strings"
)

// frontendAssets is generated by `npm run build` in the frontend directory.
//
//go:embed web/dist/*
var frontendAssets embed.FS

func (a *App) serveFrontend(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path == "/api" || strings.HasPrefix(r.URL.Path, "/api/") || strings.HasPrefix(r.URL.Path, "/files/") {
		http.NotFound(w, r)
		return
	}
	assets, err := fs.Sub(frontendAssets, "web/dist")
	if err != nil {
		http.Error(w, "前端资源不可用", http.StatusInternalServerError)
		return
	}
	name := strings.TrimPrefix(path.Clean(r.URL.Path), "/")
	if name == "." || name == "" {
		name = "index.html"
	}
	data, err := fs.ReadFile(assets, name)
	if err != nil {
		// Vue Router uses history mode, so unknown document routes return the app shell.
		name = "index.html"
		data, err = fs.ReadFile(assets, name)
	}
	if err != nil {
		http.NotFound(w, r)
		return
	}
	if contentType := mime.TypeByExtension(path.Ext(name)); contentType != "" {
		w.Header().Set("Content-Type", contentType)
	}
	if name == "index.html" {
		w.Header().Set("Cache-Control", "no-cache")
	} else {
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
	}
	_, _ = w.Write(data)
}
