package app

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"io/fs"
	"mime"
	"net/http"
	"path"
	"strconv"
	"strings"
	"sync"
)

// frontendAssets is generated by `npm run build` in the frontend directory.
//
// Include Vite chunks whose generated names begin with `_`; the default
// directory embedding rules intentionally skip dotfiles and underscore files.
//
//go:embed all:web/dist
var frontendAssets embed.FS

type frontendRepresentation struct {
	data []byte
	etag string
}

var frontendRepresentationCache sync.Map

func loadFrontendRepresentation(assets fs.FS, name, encoding string) (frontendRepresentation, error) {
	cacheKey := name + "\x00" + encoding
	if cached, ok := frontendRepresentationCache.Load(cacheKey); ok {
		return cached.(frontendRepresentation), nil
	}
	filename := name
	switch encoding {
	case "br":
		filename += ".br"
	case "gzip":
		filename += ".gz"
	}
	data, err := fs.ReadFile(assets, filename)
	if err != nil {
		return frontendRepresentation{}, err
	}
	sum := sha256.Sum256(data)
	representation := frontendRepresentation{
		data: data,
		etag: `"` + hex.EncodeToString(sum[:16]) + `"`,
	}
	frontendRepresentationCache.Store(cacheKey, representation)
	return representation, nil
}

func encodingQuality(header, target string) float64 {
	wildcard := -1.0
	for _, item := range strings.Split(header, ",") {
		parts := strings.Split(item, ";")
		name := strings.ToLower(strings.TrimSpace(parts[0]))
		quality := 1.0
		for _, parameter := range parts[1:] {
			key, value, ok := strings.Cut(strings.TrimSpace(parameter), "=")
			if ok && strings.EqualFold(key, "q") {
				parsed, err := strconv.ParseFloat(value, 64)
				if err != nil {
					quality = 0
				} else {
					quality = parsed
				}
			}
		}
		if name == target || target == "gzip" && name == "x-gzip" {
			return quality
		}
		if name == "*" {
			wildcard = quality
		}
	}
	if wildcard >= 0 {
		return wildcard
	}
	return 0
}

func preferredEncodings(header string) []string {
	brQuality := encodingQuality(header, "br")
	gzipQuality := encodingQuality(header, "gzip")
	result := make([]string, 0, 2)
	if brQuality >= gzipQuality {
		if brQuality > 0 {
			result = append(result, "br")
		}
		if gzipQuality > 0 {
			result = append(result, "gzip")
		}
	} else {
		if gzipQuality > 0 {
			result = append(result, "gzip")
		}
		if brQuality > 0 {
			result = append(result, "br")
		}
	}
	return result
}

func etagMatches(header, etag string) bool {
	for _, value := range strings.Split(header, ",") {
		value = strings.TrimSpace(value)
		if value == "*" || value == etag {
			return true
		}
	}
	return false
}

func shouldServeAppShell(r *http.Request, name string) bool {
	return (r.Method == http.MethodGet || r.Method == http.MethodHead) && path.Ext(name) == ""
}

func (a *App) serveFrontend(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path == "/api" || strings.HasPrefix(r.URL.Path, "/api/") || strings.HasPrefix(r.URL.Path, "/files/") {
		http.NotFound(w, r)
		return
	}
	assets, err := fs.Sub(frontendAssets, "web/dist")
	if err != nil {
		http.Error(w, "前端资源不可用", http.StatusInternalServerError)
		return
	}
	name := strings.TrimPrefix(path.Clean(r.URL.Path), "/")
	if name == "." || name == "" {
		name = "index.html"
	}
	representation, err := loadFrontendRepresentation(assets, name, "")
	if err != nil && shouldServeAppShell(r, name) {
		// Vue Router uses history mode, so unknown document routes return the app shell.
		name = "index.html"
		representation, err = loadFrontendRepresentation(assets, name, "")
	}
	if err != nil {
		http.NotFound(w, r)
		return
	}
	if contentType := mime.TypeByExtension(path.Ext(name)); contentType != "" {
		w.Header().Set("Content-Type", contentType)
	}
	if name == "index.html" {
		w.Header().Set("Cache-Control", "public, max-age=0, must-revalidate")
	} else if strings.HasPrefix(name, "assets/") {
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
	} else {
		w.Header().Set("Cache-Control", "public, max-age=3600, stale-while-revalidate=86400")
	}

	representations := map[string]frontendRepresentation{"": representation}
	compressedAvailable := false
	for _, encoding := range []string{"br", "gzip"} {
		if compressed, readErr := loadFrontendRepresentation(assets, name, encoding); readErr == nil {
			representations[encoding] = compressed
			compressedAvailable = true
		}
	}
	selectedEncoding := ""
	if compressedAvailable {
		w.Header().Set("Vary", "Accept-Encoding")
		for _, encoding := range preferredEncodings(r.Header.Get("Accept-Encoding")) {
			if compressed, ok := representations[encoding]; ok {
				representation = compressed
				selectedEncoding = encoding
				break
			}
		}
	}
	if selectedEncoding != "" {
		w.Header().Set("Content-Encoding", selectedEncoding)
	}
	w.Header().Set("ETag", representation.etag)
	if etagMatches(r.Header.Get("If-None-Match"), representation.etag) {
		w.WriteHeader(http.StatusNotModified)
		return
	}
	w.Header().Set("Content-Length", strconv.Itoa(len(representation.data)))
	if r.Method == http.MethodHead {
		w.WriteHeader(http.StatusOK)
		return
	}
	_, _ = w.Write(representation.data)
}
